#ifndef _EVENTS_H_
#define _EVENTS_H_

#include "cocos2d.h"
#define STEP_BUTTON_PRESSED_EVENT "STEP_BUTTON_PRESSED_EVENT"
#define STEP_BUTTON_RELEASED_EVENT "STEP_BUTTON_RELEASED_EVENT"
#define PUSH_BUTTON_PRESSED_EVENT "PUSH_BUTTON_PRESSED_EVENT"
#define PUSH_BUTTON_RELEASED_EVENT "PUSH_BUTTON_RELEASED_EVENT"

#endif // !_EVENTS_H_